version: '3.7'

services:
  postgres-database:
    image: pubdatabase
    container_name: postgres-database
    networks:
      - desafio-pub-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  account-service:
    image: viniciusleitempergher/account-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - desafio-pub-network
    depends_on:
      - naming-server
      - rabbitmq
      - postgres-database
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres-database:5432/desafiopub
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://admin:123@rabbitmq:5672/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  expending-balance-service:
    image: viniciusleitempergher/expending-balance-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - desafio-pub-network
    depends_on:
      - naming-server
      - rabbitmq
      - account-service
      - postgres-database
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres-database:5432/desafiopub
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://admin:123@rabbitmq:5672/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  incoming-balance-service:
    image: viniciusleitempergher/incoming-balance-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8200:8200"
    networks:
      - desafio-pub-network
    depends_on:
      - naming-server
      - rabbitmq
      - account-service
      - postgres-database
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres-database:5432/desafiopub
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://admin:123@rabbitmq:5672/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  api-gateway:
    image: viniciusleitempergher/api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - desafio-pub-network
    depends_on:
      - naming-server
      - rabbitmq
      - postgres-database
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://admin:123@rabbitmq:5672/
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  naming-server:
    image: viniciusleitempergher/naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - desafio-pub-network

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - desafio-pub-network
    environment:
      RABBIT_URI: amqp://admin:123@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3.8.12-management
    mem_limit: 300m
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - desafio-pub-network
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123

networks:
  desafio-pub-network: